"""Task memory shown in the web interface.

The web UI needs a compact, camera-grounded view of task-relevant objects:
for each BDDL object in the task scope, show its Qwen3-VL relative image
coordinate and head-camera forward z-depth when it is visible; otherwise show an
approximate robot-frame direction and the base spin that would face it. Public
memory records expose only the 0..1000 relative coordinate protocol.
The robot's two gripper points are also included because they are visible
reference points in the head-camera view.  For consistency with all EEF
motion tools, each gripper point is exactly the EEF pose xyz point: the
left_eef_link / right_eef_link origin.
"""

from __future__ import annotations

from functools import lru_cache
import json
import math
import os
from pathlib import Path
import time
from typing import Any, Dict, Iterable, List, Optional, Tuple
import xml.etree.ElementTree as ET

import numpy as np

from behavior_interface.coordinate_contract import COORDINATE_MAX, COORDINATE_SYSTEM

_UV_EXTEND_FRAC = 0.25
_UV_EXTEND_MIN_PX = 48
_UV_EXTEND_MAX_PX = 180
_QWEN_UV_MAX = COORDINATE_MAX
_QWEN_CLICK_MARGIN = 50

_R1PRO_URDF_REL = Path("datasets/omnigibson-robot-assets/models/r1pro/urdf/r1pro.urdf")

_ROBOT_RUNTIME_BASE_JOINT_INFO = {
    "base_footprint_x_joint": {
        "joint": "base_footprint_x_joint",
        "type": "virtual_prismatic",
        "axis": [1.0, 0.0, 0.0],
        "note": "runtime holonomic base x DOF generated by OmniGibson; not in the R1Pro URDF",
    },
    "base_footprint_y_joint": {
        "joint": "base_footprint_y_joint",
        "type": "virtual_prismatic",
        "axis": [0.0, 1.0, 0.0],
        "note": "runtime holonomic base y DOF generated by OmniGibson; not in the R1Pro URDF",
    },
    "base_footprint_z_joint": {
        "joint": "base_footprint_z_joint",
        "type": "virtual_prismatic",
        "axis": [0.0, 0.0, 1.0],
        "note": "runtime holonomic base z DOF generated by OmniGibson; not in the R1Pro URDF",
    },
    "base_footprint_rx_joint": {
        "joint": "base_footprint_rx_joint",
        "type": "virtual_revolute",
        "axis": [1.0, 0.0, 0.0],
        "note": "runtime holonomic base roll DOF generated by OmniGibson; not in the R1Pro URDF",
    },
    "base_footprint_ry_joint": {
        "joint": "base_footprint_ry_joint",
        "type": "virtual_revolute",
        "axis": [0.0, 1.0, 0.0],
        "note": "runtime holonomic base pitch DOF generated by OmniGibson; not in the R1Pro URDF",
    },
    "base_footprint_rz_joint": {
        "joint": "base_footprint_rz_joint",
        "type": "virtual_revolute",
        "axis": [0.0, 0.0, 1.0],
        "note": "runtime holonomic base yaw DOF generated by OmniGibson; not in the R1Pro URDF",
    },
}

_ROBOT_RUNTIME_JOINT_GROUPS = (
    ("base_pose", tuple(_ROBOT_RUNTIME_BASE_JOINT_INFO.keys())),
    ("trunk", tuple(f"torso_joint{i}" for i in range(1, 5))),
    ("left_arm", tuple(f"left_arm_joint{i}" for i in range(1, 8))),
    ("left_tool_roll", ("left_arm_joint8",)),
    ("left_gripper", tuple(f"left_gripper_finger_joint{i}" for i in range(1, 3))),
    ("right_arm", tuple(f"right_arm_joint{i}" for i in range(1, 8))),
    ("right_tool_roll", ("right_arm_joint8",)),
    ("right_gripper", tuple(f"right_gripper_finger_joint{i}" for i in range(1, 3))),
)

_ROBOT_URDF_WHEEL_RELATION_JOINTS = (
    "steer_motor_joint1", "wheel_motor_joint1",
    "steer_motor_joint2", "wheel_motor_joint2",
    "steer_motor_joint3", "wheel_motor_joint3",
)

_ROBOT_FIXED_RELATION_JOINTS = (
    "zed_joint",
    "left_arm_base_joint",
    "right_arm_base_joint",
)


def _to_np(x) -> np.ndarray:
    if hasattr(x, "detach"):
        x = x.detach().cpu().numpy()
    return np.asarray(x, dtype=np.float64)


def _to_np_preserve_dtype(x) -> np.ndarray:
    if hasattr(x, "detach"):
        x = x.detach().cpu().numpy()
    return np.asarray(x)


def _quat_to_mat(q) -> np.ndarray:
    x, y, z, w = [float(v) for v in np.asarray(q, dtype=np.float64).reshape(4)]
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
        [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
        [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
    ], dtype=np.float64)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


@lru_cache(maxsize=1)
def _challenge_task_instructions() -> Dict[str, str]:
    """Return BEHAVIOR Challenge task_name -> natural-language task instruction."""
    out: Dict[str, str] = {}
    try:
        from .challenge_tasks import BEHAVIOR_CHALLENGE_2026_TASKS
    except Exception:
        BEHAVIOR_CHALLENGE_2026_TASKS = ()

    for task in BEHAVIOR_CHALLENGE_2026_TASKS:
        name = str(task.get("name") or "").strip()
        instruction = str(task.get("instruction") or "").strip()
        if name and instruction:
            out[name] = instruction
    if out:
        return out

    # Legacy fallback for checkouts that only have the 2025 sampled episodes.
    try:
        from .challenge_tasks import BEHAVIOR_CHALLENGE_2025_TASKS
    except Exception:
        return {}
    id_to_name = {
        int(task["id"]): str(task["name"])
        for task in BEHAVIOR_CHALLENGE_2025_TASKS
        if "id" in task and "name" in task
    }
    episodes_path = (
        _repo_root()
        / "datasets"
        / "2025-challenge-task-instances"
        / "metadata"
        / "episodes.jsonl"
    )
    try:
        with episodes_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                task_id = int(rec.get("episode_index", 0)) // 10000
                task_name = id_to_name.get(task_id)
                tasks = rec.get("tasks") or []
                instruction = " ".join(str(x).strip() for x in tasks if str(x).strip())
                if task_name and instruction and task_name not in out:
                    out[task_name] = " ".join(instruction.split())
                if len(out) >= len(id_to_name):
                    break
    except Exception:
        return {}
    return out


def _task_instruction(task_name: str) -> str:
    task_name = str(task_name or "").strip()
    if not task_name:
        return "unknown task"
    return _challenge_task_instructions().get(task_name) or task_name.replace("_", " ")


_TASK_GOALS_ONLY_MODE = "task_goals_only"


def memory_mode() -> str:
    """Return the model-facing memory mode selected for this process."""
    value = str(os.environ.get("BEHAVIOR_MEMORY_MODE", "full") or "full")
    value = value.strip().lower().replace("-", "_")
    if value in {_TASK_GOALS_ONLY_MODE, "task_and_goals_only", "ablation"}:
        return _TASK_GOALS_ONLY_MODE
    return "full"


def task_goals_only_memory_enabled() -> bool:
    return memory_mode() == _TASK_GOALS_ONLY_MODE


def _public_bddl_completion(goals: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    goals = goals if isinstance(goals, dict) else {}
    conditions = []
    for fallback_index, item in enumerate(goals.get("items") or []):
        if not isinstance(item, dict):
            continue
        condition = str(item.get("full") or item.get("label") or "").strip()
        conditions.append({
            "index": int(item.get("index", fallback_index)),
            "condition": condition,
            "satisfied": bool(item.get("satisfied", False)),
        })
    satisfied = sum(1 for item in conditions if item["satisfied"])
    total = len(conditions)
    if not conditions:
        try:
            satisfied = max(0, int(goals.get("satisfied", 0)))
        except (TypeError, ValueError):
            satisfied = 0
        try:
            total = max(0, int(goals.get("total", 0)))
        except (TypeError, ValueError):
            total = 0
        satisfied = min(satisfied, total)
    return {
        "complete": bool(goals.get("complete", False)),
        "satisfied": satisfied,
        "total": total,
        "conditions": conditions,
    }


def build_task_goals_only_memory(
    *,
    task_name: str = "",
    task_instruction: str = "",
    goals: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build memory with no simulator-derived object or robot geometry."""
    instruction = str(task_instruction or _task_instruction(task_name)).strip()
    return {
        "task_instruction": instruction,
        "bddl_completion": _public_bddl_completion(goals),
    }


def format_task_goals_only_memory(mem: Dict[str, Any]) -> str:
    instruction = str(mem.get("task_instruction") or "").strip()
    bddl = mem.get("bddl_completion")
    bddl = bddl if isinstance(bddl, dict) else _public_bddl_completion(None)
    satisfied = int(bddl.get("satisfied", 0) or 0)
    total = int(bddl.get("total", 0) or 0)
    lines = [
        "Task instruction:",
        instruction,
        "",
        "BDDL completion:",
        f"complete: {str(bool(bddl.get('complete', False))).lower()}",
        f"satisfied: {satisfied}/{total}",
    ]
    for item in bddl.get("conditions") or []:
        if not isinstance(item, dict):
            continue
        mark = "x" if item.get("satisfied") else " "
        condition = str(item.get("condition") or "").strip()
        lines.append(f"- [{mark}] {condition}")
    return "\n".join(lines).rstrip()


def sanitize_model_payload(
    payload: Any,
    *,
    task_name: str,
    goals: Optional[Dict[str, Any]],
) -> Any:
    """Remove privileged task geometry from a model-visible API payload."""
    public_memory = build_task_goals_only_memory(task_name=task_name, goals=goals)
    public_text = format_task_goals_only_memory(public_memory)

    def _sanitize(value: Any) -> Any:
        if isinstance(value, dict):
            clean: Dict[str, Any] = {}
            for key, child in value.items():
                if key == "memory":
                    clean[key] = dict(public_memory)
                elif key == "memory_text":
                    clean[key] = public_text
                elif key == "tro":
                    clean[key] = {}
                else:
                    clean[key] = _sanitize(child)
            return clean
        if isinstance(value, list):
            return [_sanitize(child) for child in value]
        if isinstance(value, tuple):
            return tuple(_sanitize(child) for child in value)
        return value

    return _sanitize(payload)


def _round_float(v: Any, ndigits: int = 4) -> Optional[float]:
    try:
        f = float(v)
    except Exception:
        return None
    if not math.isfinite(f):
        return None
    return round(f, ndigits)


def _norm_angle_deg(deg: Any) -> Optional[float]:
    try:
        f = float(deg)
    except Exception:
        return None
    if not math.isfinite(f):
        return None
    return (f + 180.0) % 360.0 - 180.0


def _direction_from_spin_deg(spin_deg: Optional[float]) -> str:
    if spin_deg is None or not math.isfinite(float(spin_deg)):
        return "unknown"
    spin = float(spin_deg)
    a = abs(spin)
    if a <= 12.0:
        return "front"
    if a >= 168.0:
        return "back"
    side = "left" if spin > 0.0 else "right"
    if a < 60.0:
        return f"front-{side}"
    if a <= 120.0:
        return side
    return f"back-{side}"


def _numeric_robot_pose(world: Any, robot_pose: Dict[str, Any]) -> Tuple[Dict[str, float], str]:
    pose = dict(robot_pose or {})
    source = "server_cache"

    def num(key: str) -> Optional[float]:
        try:
            val = float(pose.get(key))
        except Exception:
            return None
        return val if math.isfinite(val) else None

    if num("x") is None or num("y") is None or num("z") is None or num("yaw_deg") is None:
        try:
            wp = world.robot_pose()
            pose = {
                "x": float(wp.pos[0]),
                "y": float(wp.pos[1]),
                "z": float(wp.pos[2]),
                "yaw_deg": math.degrees(float(wp.yaw)),
            }
            source = "world.robot_pose"
        except Exception:
            pose = {
                "x": float(num("x") or 0.0),
                "y": float(num("y") or 0.0),
                "z": float(num("z") or 0.0),
                "yaw_deg": float(num("yaw_deg") or 0.0),
            }
            source = "fallback_zero"
    return {
        "x": float(pose.get("x", 0.0)),
        "y": float(pose.get("y", 0.0)),
        "z": float(pose.get("z", 0.0)),
        "yaw_deg": float(pose.get("yaw_deg", 0.0)),
    }, source


def _pitch_hint_for_center(
    center: np.ndarray,
    cam: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """Return a q3/adjust_pitch hint to vertically center an object.

    Convention matches /api/v2/adjust_pitch: positive degree means look up
    (increase head/camera elevation), negative means look down.  The estimate
    compares the target elevation from the current head camera position against
    the current head optical-axis elevation.  It is independent of yaw, so it
    remains meaningful together with spin_to_view for off-screen objects.
    """
    if not isinstance(cam, dict) or cam.get("pos") is None or cam.get("quat") is None:
        return {
            "pitch_to_view_deg": None,
            "target_pitch_deg": None,
            "camera_pitch_deg": None,
            "pitch_hint_reason": "no_head_camera_pose",
        }
    try:
        cam_pos = np.asarray(cam.get("pos"), dtype=np.float64).reshape(3)
        cam_quat = np.asarray(cam.get("quat"), dtype=np.float64).reshape(4)
        target = np.asarray(center, dtype=np.float64).reshape(3)
        if not (np.all(np.isfinite(cam_pos)) and np.all(np.isfinite(cam_quat)) and np.all(np.isfinite(target))):
            raise ValueError("non_finite_pose_or_target")
        delta = target - cam_pos
        horiz = math.hypot(float(delta[0]), float(delta[1]))
        if horiz < 1e-5:
            target_pitch = 90.0 if float(delta[2]) >= 0.0 else -90.0
        else:
            target_pitch = math.degrees(math.atan2(float(delta[2]), horiz))
        R = _quat_to_mat(cam_quat)
        optical_world = R @ np.array([0.0, 0.0, -1.0], dtype=np.float64)
        optical_h = math.hypot(float(optical_world[0]), float(optical_world[1]))
        if optical_h < 1e-8:
            camera_pitch = 90.0 if float(optical_world[2]) >= 0.0 else -90.0
        else:
            camera_pitch = math.degrees(math.atan2(float(optical_world[2]), optical_h))
        pitch_delta = _norm_angle_deg(float(target_pitch) - float(camera_pitch))
        # adjust_pitch endpoint rejects |degree| > 45; expose the raw estimate
        # and a safe command-sized value separately.
        pitch_cmd = max(-45.0, min(45.0, float(pitch_delta)))
        return {
            "pitch_to_view_deg": _round_float(pitch_cmd, 1),
            "pitch_to_view_raw_deg": _round_float(pitch_delta, 1),
            "target_pitch_deg": _round_float(target_pitch, 1),
            "camera_pitch_deg": _round_float(camera_pitch, 1),
            "pitch_hint_reason": "target_elevation_minus_camera_elevation",
            "pitch_sign": "positive means look up / adjust_pitch(degree>0); negative means look down",
        }
    except Exception as exc:
        return {
            "pitch_to_view_deg": None,
            "target_pitch_deg": None,
            "camera_pitch_deg": None,
            "pitch_hint_reason": str(exc),
        }


def _spin_hint_for_center(
    center: np.ndarray,
    robot_pos: np.ndarray,
    robot_yaw_deg: float,
) -> Dict[str, Any]:
    center = np.asarray(center, dtype=np.float64).reshape(3)
    robot_pos = np.asarray(robot_pos, dtype=np.float64).reshape(3)
    dx = float(center[0] - robot_pos[0])
    dy = float(center[1] - robot_pos[1])
    dist_xy = math.hypot(dx, dy)
    if not math.isfinite(dist_xy) or dist_xy < 1e-5:
        return {
            "approx_dir": "at-base",
            "spin_to_view_deg": 0.0,
            "relative_bearing_deg": 0.0,
            "target_yaw_deg": _round_float(robot_yaw_deg, 1),
            "bearing_world_deg": _round_float(robot_yaw_deg, 1),
            "robot_xy_distance_m": _round_float(dist_xy, 3),
        }
    bearing_world = math.degrees(math.atan2(dy, dx))
    spin = _norm_angle_deg(bearing_world - float(robot_yaw_deg))
    target_yaw = _norm_angle_deg(float(robot_yaw_deg) + float(spin or 0.0))
    return {
        "approx_dir": _direction_from_spin_deg(spin),
        "spin_to_view_deg": _round_float(spin, 1),
        "relative_bearing_deg": _round_float(spin, 1),
        "target_yaw_deg": _round_float(target_yaw, 1),
        "bearing_world_deg": _round_float(bearing_world, 1),
        "robot_xy_distance_m": _round_float(dist_xy, 3),
    }


def _hidden_memory_record(
    *,
    center: np.ndarray,
    robot_pos: np.ndarray,
    robot_yaw_deg: float,
    robot_distance_m: float,
    reason: str,
    cam: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    hint = _spin_hint_for_center(center, robot_pos, robot_yaw_deg)
    pitch_hint = _pitch_hint_for_center(center, cam)
    return {
        "visible": False,
        "uv": None,
        "u": None,
        "v": None,
        "coord_system": COORDINATE_SYSTEM,
        "depth": None,
        "depth_kind": "not_visible",
        "reason": str(reason or "not_visible"),
        "approx_dir": hint.get("approx_dir", "unknown"),
        "spin_to_view_deg": hint.get("spin_to_view_deg"),
        "relative_bearing_deg": hint.get("relative_bearing_deg"),
        "target_yaw_deg": hint.get("target_yaw_deg"),
        "bearing_world_deg": hint.get("bearing_world_deg"),
        "pitch_to_view_deg": pitch_hint.get("pitch_to_view_deg"),
        "pitch_to_view_raw_deg": pitch_hint.get("pitch_to_view_raw_deg"),
        "target_pitch_deg": pitch_hint.get("target_pitch_deg"),
        "camera_pitch_deg": pitch_hint.get("camera_pitch_deg"),
        "pitch_hint_reason": pitch_hint.get("pitch_hint_reason"),
        "robot_distance_m": _round_float(robot_distance_m, 3),
        "robot_xy_distance_m": hint.get("robot_xy_distance_m"),
        "spin_sign": "positive means turn left / counterclockwise in move_in_robot_coord",
        "pitch_sign": "positive means look up; negative means look down in adjust_pitch",
    }


def _joint_attr_float(joint_el: ET.Element, tag: str, attr: str) -> Optional[float]:
    child = joint_el.find(tag)
    if child is None:
        return None
    val = child.get(attr)
    if val is None or val == "":
        return None
    try:
        return float(val)
    except Exception:
        return None


def _joint_child_attr(joint_el: ET.Element, tag: str, attr: str, default: str = "") -> str:
    child = joint_el.find(tag)
    if child is None:
        return default
    return str(child.get(attr) or default)


@lru_cache(maxsize=4)
def _r1pro_urdf_joint_map() -> Dict[str, Dict[str, Any]]:
    """Parse the R1Pro URDF once so Memory can explain joint/link relations."""
    path = _repo_root() / _R1PRO_URDF_REL
    out: Dict[str, Dict[str, Any]] = {}
    try:
        root = ET.parse(path).getroot()
    except Exception:
        return out
    for joint_el in root.findall("joint"):
        name = str(joint_el.get("name") or "")
        if not name:
            continue
        parent = _joint_child_attr(joint_el, "parent", "link")
        child = _joint_child_attr(joint_el, "child", "link")
        axis_s = _joint_child_attr(joint_el, "axis", "xyz", "0 0 0")
        axis = []
        for part in axis_s.split():
            try:
                axis.append(float(part))
            except Exception:
                axis.append(0.0)
        while len(axis) < 3:
            axis.append(0.0)
        out[name] = {
            "joint": name,
            "type": str(joint_el.get("type") or ""),
            "parent": parent,
            "child": child,
            "axis": [round(float(x), 6) for x in axis[:3]],
            "limit": {
                "lower": _joint_attr_float(joint_el, "limit", "lower"),
                "upper": _joint_attr_float(joint_el, "limit", "upper"),
            },
        }
    return out


def _joint_qpos_by_name(robot: Any) -> Tuple[Dict[str, float], List[str]]:
    if robot is None:
        return {}, []
    try:
        names = [str(n) for n in list(getattr(robot, "joints", {}).keys())]
        qpos = _to_np(robot.get_joint_positions()).reshape(-1)
    except Exception:
        return {}, []
    by_name: Dict[str, float] = {}
    for idx, name in enumerate(names):
        if idx >= qpos.size:
            break
        val = _round_float(qpos[idx], 5)
        if val is not None:
            by_name[name] = val
    return by_name, names


def _joint_record(joint_name: str, q_by_name: Dict[str, float], urdf: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    info = dict(
        urdf.get(joint_name)
        or _ROBOT_RUNTIME_BASE_JOINT_INFO.get(joint_name)
        or {"joint": joint_name}
    )
    q = q_by_name.get(joint_name)
    info["qpos"] = q
    info["observed"] = q is not None
    return info


def _build_robot_joint_observation(world) -> Dict[str, Any]:
    """Current qpos grouped by the R1Pro URDF control chains."""
    robot = getattr(world, "robot", None)
    urdf = _r1pro_urdf_joint_map()
    q_by_name, runtime_names = _joint_qpos_by_name(robot)
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for group_name, joint_names in _ROBOT_RUNTIME_JOINT_GROUPS:
        groups[group_name] = [
            _joint_record(jn, q_by_name, urdf)
            for jn in joint_names
        ]
    fixed_relations = [
        _joint_record(jn, q_by_name, urdf)
        for jn in _ROBOT_FIXED_RELATION_JOINTS
        if jn in urdf
    ]
    urdf_wheel_relations = [
        _joint_record(jn, q_by_name, urdf)
        for jn in _ROBOT_URDF_WHEEL_RELATION_JOINTS
        if jn in urdf
    ]
    observed = sum(
        1
        for joints in groups.values()
        for rec in joints
        if rec.get("observed")
    )
    expected = sum(len(joints) for joints in groups.values())
    return {
        "ok": robot is not None and bool(q_by_name),
        "robot_type": type(robot).__name__ if robot is not None else None,
        "source": "runtime robot.get_joint_positions() matched by joint name; relations from R1Pro URDF",
        "urdf": str(_R1PRO_URDF_REL),
        "units": {
            "revolute": "rad",
            "continuous": "rad",
            "prismatic": "m",
            "virtual_revolute": "rad",
            "virtual_prismatic": "m",
        },
        "observed_count": observed,
        "expected_count": expected,
        "runtime_joint_count": len(runtime_names),
        "runtime_joint_names": runtime_names,
        "groups": groups,
        "fixed_relations": fixed_relations,
        "urdf_wheel_relations": urdf_wheel_relations,
    }


def _project_point(
    cam_pos: np.ndarray,
    cam_quat: np.ndarray,
    p_world: np.ndarray,
    w: int,
    h: int,
    fl: float,
    ha: float,
) -> Optional[Dict[str, float]]:
    """Project a world point into the USD camera image. Camera looks along -Z."""
    R = _quat_to_mat(cam_quat)
    p_cam = R.T @ (np.asarray(p_world, dtype=np.float64).reshape(3) - cam_pos)
    if float(p_cam[2]) >= -1e-6:
        return None
    fx = float(fl) / float(ha) * float(w)
    fy = fx
    u = fx * float(p_cam[0]) / (-float(p_cam[2])) + float(w) / 2.0
    v = float(h) / 2.0 - fy * float(p_cam[1]) / (-float(p_cam[2]))
    return {"u": u, "v": v, "camera_depth_m": -float(p_cam[2])}


def _aabb_points(lo: Optional[np.ndarray], hi: Optional[np.ndarray], center: np.ndarray) -> List[np.ndarray]:
    if lo is None or hi is None:
        return [center]
    lo = np.asarray(lo, dtype=np.float64).reshape(3)
    hi = np.asarray(hi, dtype=np.float64).reshape(3)
    c = (lo + hi) * 0.5
    pts: List[np.ndarray] = [c]
    for x in (lo[0], hi[0]):
        for y in (lo[1], hi[1]):
            for z in (lo[2], hi[2]):
                pts.append(np.array([x, y, z], dtype=np.float64))
    pts.extend([
        np.array([lo[0], c[1], c[2]], dtype=np.float64),
        np.array([hi[0], c[1], c[2]], dtype=np.float64),
        np.array([c[0], lo[1], c[2]], dtype=np.float64),
        np.array([c[0], hi[1], c[2]], dtype=np.float64),
        np.array([c[0], c[1], lo[2]], dtype=np.float64),
        np.array([c[0], c[1], hi[2]], dtype=np.float64),
    ])
    return pts


def _finite_patch_depth(depth: np.ndarray, u: int, v: int, radius: int = 2) -> Optional[float]:
    h, w = depth.shape[:2]
    u0, u1 = max(0, int(u) - radius), min(w, int(u) + radius + 1)
    v0, v1 = max(0, int(v) - radius), min(h, int(v) + radius + 1)
    patch = np.asarray(depth[v0:v1, u0:u1], dtype=np.float64).reshape(-1)
    patch = patch[np.isfinite(patch) & (patch > 0.01) & (patch < 80.0)]
    if patch.size == 0:
        return None
    return float(np.median(patch))


def _depth_visible(
    depth: Optional[np.ndarray],
    proj: Dict[str, float],
    radius_m: float,
) -> Tuple[bool, Optional[float], str]:
    if depth is None:
        return True, None, "projection_only"
    u = int(round(float(proj["u"])))
    v = int(round(float(proj["v"])))
    observed = _finite_patch_depth(depth, u, v)
    if observed is None:
        return False, None, "no_depth_at_pixel"
    expected = float(proj["camera_depth_m"])
    front_tol = max(0.08, float(radius_m) + 0.06)
    back_tol = 0.12
    if expected - front_tol <= observed <= expected + back_tol:
        return True, observed, "depth_visible"
    return False, observed, "depth_occluded"


def _uv_margin_px(w: int, h: int) -> int:
    if w <= 0 or h <= 0:
        return 0
    return int(round(max(_UV_EXTEND_MIN_PX, min(_UV_EXTEND_MAX_PX, max(w, h) * _UV_EXTEND_FRAC))))


def _pixel_to_qwen_uv(u_px: float, v_px: float, w: int, h: int) -> Tuple[int, int]:
    """Convert image pixel coordinates to Qwen3-VL's 0..1000 relative coords.

    Raw projected pixel uv may intentionally use an extended image margin for
    internal visibility/heading logic.  The formatted MEMORY shown to the VLM,
    however, must stay in Qwen's nominal 0..1000 coordinate range because the
    model is expected to output those coordinates directly.
    """
    if w <= 1 or h <= 1:
        u = int(round(float(u_px)))
        v = int(round(float(v_px)))
    else:
        u = int(round(float(u_px) / float(w - 1) * float(_QWEN_UV_MAX)))
        v = int(round(float(v_px) / float(h - 1) * float(_QWEN_UV_MAX)))
    u = max(0, min(int(_QWEN_UV_MAX), u))
    v = max(0, min(int(_QWEN_UV_MAX), v))
    return u, v


def _qwen_uv_clickable(u: int, v: int) -> bool:
    """Whether a model-facing point is safe to present as clickable UVD.

    MEMORY may use extended projections internally to compute turn hints for
    partially/off-screen objects.  Those edge-clamped points are bad action
    targets, so do not expose them as visible object UVD.
    """
    try:
        uu = int(u)
        vv = int(v)
    except Exception:
        return False
    m = int(_QWEN_CLICK_MARGIN)
    return m <= uu <= int(_QWEN_UV_MAX) - m and m <= vv <= int(_QWEN_UV_MAX) - m


def _uv_margin_qwen(w: int, h: int, margin_px: Optional[int] = None) -> int:
    if w <= 1 or h <= 1:
        return 0
    m = _uv_margin_px(w, h) if margin_px is None else int(max(0, margin_px))
    denom = float(max(1, min(w - 1, h - 1)))
    return int(round(float(m) / denom * float(_QWEN_UV_MAX)))


def _uv_in_image(proj: Dict[str, float], w: int, h: int) -> bool:
    return 0 <= float(proj["u"]) < float(w) and 0 <= float(proj["v"]) < float(h)


def _uv_in_extended_range(proj: Dict[str, float], w: int, h: int, margin_px: int) -> bool:
    m = float(max(0, margin_px))
    return -m <= float(proj["u"]) < float(w) + m and -m <= float(proj["v"]) < float(h) + m


def _task_scope_objects(world, tro: Dict[str, Any]) -> Iterable[Tuple[str, Any]]:
    scope = {}
    try:
        scope = getattr(world.env.task, "object_scope", None) or {}
    except Exception:
        scope = {}
    keys = list(tro.keys()) if tro else list(scope.keys())
    seen = set()
    for key in keys:
        if key in seen:
            continue
        seen.add(key)
        ent = scope.get(key)
        obj = getattr(ent, "unwrapped", ent) if ent is not None else None
        yield str(key), obj


def _object_geometry(obj: Any, tro_entry: Dict[str, Any]) -> Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]:
    lo = hi = None
    if obj is not None:
        try:
            aabb = obj.aabb
            lo = _to_np(aabb[0]).reshape(3)
            hi = _to_np(aabb[1]).reshape(3)
            return (lo + hi) * 0.5, lo, hi
        except Exception:
            pass
        try:
            pos, _quat = obj.get_position_orientation()
            return _to_np(pos).reshape(3), None, None
        except Exception:
            pass
    pos = np.asarray(tro_entry.get("pos", [0.0, 0.0, 0.0]), dtype=np.float64).reshape(3)
    return pos, None, None


def _object_radius(lo: Optional[np.ndarray], hi: Optional[np.ndarray]) -> float:
    if lo is None or hi is None:
        return 0.10
    return max(0.04, float(np.linalg.norm(np.asarray(hi) - np.asarray(lo))) * 0.5)


def _select_head_projection(
    *,
    head: Optional[Any],
    cam: Dict[str, Any],
    depth: Optional[np.ndarray],
    center: np.ndarray,
    lo: Optional[np.ndarray],
    hi: Optional[np.ndarray],
    radius_m: float,
    use_depth: bool = True,
) -> Tuple[Optional[Dict[str, float]], str, Optional[float]]:
    reason = "no_head_camera" if head is None else "out_of_view"
    chosen = None
    observed_depth = None
    if head is None:
        return None, reason, None

    candidates = []
    w = int(cam["image_width"])
    h = int(cam["image_height"])
    margin_px = _uv_margin_px(w, h)
    for pt in _aabb_points(lo, hi, center):
        proj = _project_point(
            cam["pos"], cam["quat"], pt, w, h,
            float(cam["focal_length"]), float(cam["horizontal_aperture"]),
        )
        if proj is None:
            continue
        if not _uv_in_extended_range(proj, w, h, margin_px):
            continue
        proj = dict(proj)
        proj["in_image"] = _uv_in_image(proj, w, h)
        proj["uv_margin_px"] = margin_px
        if use_depth and bool(proj["in_image"]):
            ok, obs_d, why = _depth_visible(depth, proj, radius_m)
        elif use_depth:
            ok, obs_d, why = True, None, "projection_extended"
        else:
            why = "projection_visible" if bool(proj["in_image"]) else "projection_extended"
            ok, obs_d = True, None
        candidates.append((ok, obs_d, why, proj))
        if ok:
            chosen = proj
            observed_depth = obs_d
            reason = why
            break
    if chosen is None and candidates:
        reason = candidates[0][2]
    return chosen, reason, observed_depth


def _gripper_memory_points(world) -> Iterable[Tuple[str, np.ndarray, Dict[str, Any]]]:
    robot = getattr(world, "robot", None)
    arms = list(getattr(robot, "arm_names", []) or ["left", "right"])
    arms = [str(a).lower() for a in arms if str(a).lower() in ("left", "right")]
    if not arms:
        arms = ["left", "right"]
    for arm in arms:
        key = f"{arm}_gripper"
        try:
            pose = world.eef_pose(arm=arm)
            eef_pos = np.asarray(pose.get("pos"), dtype=np.float64).reshape(3)
            eef_quat = np.asarray(pose.get("quat"), dtype=np.float64).reshape(4)
            if not (np.all(np.isfinite(eef_pos)) and np.all(np.isfinite(eef_quat))):
                raise ValueError("non-finite eef pose")
            center = eef_pos
            yield key, center, {
                "arm": arm,
                "category": "gripper",
                "scene_name": key,
                "point_kind": "eef_pose_origin",
                "eef_pos": eef_pos,
                "eef_quat": eef_quat,
            }
        except Exception as e:
            yield key, np.zeros(3, dtype=np.float64), {
                "arm": arm,
                "category": "gripper",
                "scene_name": key,
                "point_kind": "eef_pose_origin",
                "error": str(e),
            }


def _read_head_depth(head) -> Tuple[Optional[np.ndarray], str]:
    have = list(getattr(head, "modalities", []))
    if "depth_linear" not in have:
        try:
            head.add_modality("depth_linear")
        except Exception:
            return None, "no_depth_modality"
        return None, "depth_requested"
    try:
        obs, _info = head.get_obs()
    except Exception:
        return None, "depth_unavailable"
    depth = obs.get("depth_linear")
    if depth is None:
        return None, "depth_unavailable"
    depth = _to_np_preserve_dtype(depth)
    if depth.ndim == 3:
        depth = depth[..., 0]
    # Keep the sensor dtype here. Converting a 720x720 depth frame to float64
    # allocates about 4 MiB on every periodic refresh; only the tiny sampled
    # patch needs float64 precision in _finite_patch_depth().
    return np.asarray(depth), "depth_linear"


def _head_camera(world) -> Tuple[Optional[Any], Dict[str, Any]]:
    try:
        from behavior_interface.head_capture import get_head_sensor, head_intrinsics_tuple

        head = get_head_sensor(world)
        if head is None:
            return None, {"reason": "no_head_camera"}
        pos, quat = head.get_position_orientation()
        fl, ha, w, h = head_intrinsics_tuple(head)
        return head, {
            "pos": _to_np(pos).reshape(3),
            "quat": _to_np(quat).reshape(4),
            "focal_length": float(fl),
            "horizontal_aperture": float(ha),
            "image_width": int(w),
            "image_height": int(h),
        }
    except Exception as e:
        return None, {"reason": str(e)}


def build_memory(
    world,
    *,
    task_name: str = "",
    robot_pose: Optional[Dict[str, Any]] = None,
    tro: Optional[Dict[str, Any]] = None,
    tick: Optional[int] = None,
    head: Optional[Any] = None,
    head_camera: Optional[Dict[str, Any]] = None,
    depth_linear: Optional[np.ndarray] = None,
    image_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Build web memory for task-relevant objects.

    ``objects`` maps each task object to a visible uv-depth record, or to an
    invisible heading record with ``spin_to_view_deg``.  Positive spin matches
    ``move_in_robot_coord(spin=...)``: turn left / counterclockwise.
    """
    tro = dict(tro or {})
    robot_pose, robot_pose_source = _numeric_robot_pose(world, dict(robot_pose or {}))
    robot_pos = np.array([
        float(robot_pose.get("x", 0.0)),
        float(robot_pose.get("y", 0.0)),
        float(robot_pose.get("z", 0.0)),
    ], dtype=np.float64)
    robot_yaw_deg = float(robot_pose.get("yaw_deg", 0.0))
    robot_joints = _build_robot_joint_observation(world)
    depth = None
    depth_source = "none"
    if head_camera is not None:
        cam = dict(head_camera)
        if "pos" in cam:
            cam["pos"] = _to_np(cam["pos"]).reshape(3)
        if "quat" in cam:
            cam["quat"] = _to_np(cam["quat"]).reshape(4)
        if depth_linear is not None:
            depth = _to_np_preserve_dtype(depth_linear)
            if depth.ndim == 3:
                depth = depth[..., 0]
            depth_source = "capture_depth_linear"
        else:
            depth_source = "capture_no_depth"
        # Do not re-read the sensor when an explicit capture camera is supplied:
        # this keeps MEMORY UVD bound to the exact image/depth/camera pose that
        # was just saved under image_id.
        head = head if head is not None else object()
    else:
        head, cam = _head_camera(world)
        if head is not None:
            depth, depth_source = _read_head_depth(head)

    objects: Dict[str, Dict[str, Any]] = {}
    details: Dict[str, Dict[str, Any]] = {}
    total = visible = 0

    for key, obj in _task_scope_objects(world, tro):
        total += 1
        entry = tro.get(key, {}) if isinstance(tro.get(key), dict) else {}
        center, lo, hi = _object_geometry(obj, entry)
        category = str(getattr(obj, "category", entry.get("category", "")) or "")
        scene_name = str(getattr(obj, "name", entry.get("scene_name", "")) or "")
        radius = _object_radius(lo, hi)
        chosen, reason, observed_depth = _select_head_projection(
            head=head, cam=cam, depth=depth, center=center, lo=lo, hi=hi,
            radius_m=radius, use_depth=True,
        )

        robot_depth = float(np.linalg.norm(center - robot_pos))
        spin_hint = _spin_hint_for_center(center, robot_pos, robot_yaw_deg)
        pitch_hint = _pitch_hint_for_center(center, cam)
        chosen_clickable = False
        qwen_u = qwen_v = None
        u = v = None
        if chosen is not None:
            u = int(round(float(chosen["u"])))
            v = int(round(float(chosen["v"])))
            qwen_u, qwen_v = _pixel_to_qwen_uv(
                u, v,
                int(cam.get("image_width", 0) or 0),
                int(cam.get("image_height", 0) or 0),
            )
            chosen_clickable = bool(chosen.get("in_image")) and _qwen_uv_clickable(qwen_u, qwen_v)
        if chosen is not None and chosen_clickable:
            camera_depth = float(chosen["camera_depth_m"])
            objects[key] = {
                "visible": True,
                "uv": [qwen_u, qwen_v],
                "u": qwen_u,
                "v": qwen_v,
                "coord_system": COORDINATE_SYSTEM,
                "depth": round(camera_depth, 3),
                "depth_kind": "camera_forward_z",
                "clickable": True,
            }
            visible += 1
        else:
            hidden_reason = reason
            if chosen is not None and not chosen_clickable:
                hidden_reason = "projection_clipped_not_clickable"
            objects[key] = _hidden_memory_record(
                center=center,
                robot_pos=robot_pos,
                robot_yaw_deg=robot_yaw_deg,
                robot_distance_m=robot_depth,
                reason=hidden_reason,
                cam=cam,
            )
        details[key] = {
            "visible": bool(chosen is not None and chosen_clickable),
            "clickable": bool(chosen is not None and chosen_clickable),
            "reason": reason,
            "category": category,
            "scene_name": scene_name,
            "center_world": [round(float(x), 4) for x in center.tolist()],
            "robot_distance_m": round(robot_depth, 3),
            "robot_xy_distance_m": spin_hint.get("robot_xy_distance_m"),
            "approx_dir": spin_hint.get("approx_dir"),
            "spin_to_view_deg": spin_hint.get("spin_to_view_deg"),
            "relative_bearing_deg": spin_hint.get("relative_bearing_deg"),
            "target_yaw_deg": spin_hint.get("target_yaw_deg"),
            "bearing_world_deg": spin_hint.get("bearing_world_deg"),
            "pitch_to_view_deg": pitch_hint.get("pitch_to_view_deg"),
            "pitch_to_view_raw_deg": pitch_hint.get("pitch_to_view_raw_deg"),
            "target_pitch_deg": pitch_hint.get("target_pitch_deg"),
            "camera_pitch_deg": pitch_hint.get("camera_pitch_deg"),
            "pitch_hint_reason": pitch_hint.get("pitch_hint_reason"),
            "camera_depth_m": (
                round(float(chosen["camera_depth_m"]), 3) if chosen is not None else None
            ),
            "observed_depth_linear_m": (
                round(float(observed_depth), 3) if observed_depth is not None else None
            ),
        }

    for key, center, meta in _gripper_memory_points(world):
        total += 1
        chosen = None
        observed_depth = None
        reason = meta.get("error") or ("no_head_camera" if head is None else "out_of_view")
        if not meta.get("error"):
            chosen, reason, observed_depth = _select_head_projection(
                head=head, cam=cam, depth=depth, center=center, lo=None, hi=None,
                radius_m=0.08, use_depth=False,
            )

        robot_depth = float(np.linalg.norm(center - robot_pos))
        spin_hint = _spin_hint_for_center(center, robot_pos, robot_yaw_deg)
        pitch_hint = _pitch_hint_for_center(center, cam)
        if chosen is not None:
            u = int(round(float(chosen["u"])))
            v = int(round(float(chosen["v"])))
            qwen_u, qwen_v = _pixel_to_qwen_uv(
                u, v,
                int(cam.get("image_width", 0) or 0),
                int(cam.get("image_height", 0) or 0),
            )
            camera_depth = float(chosen["camera_depth_m"])
            objects[key] = {
                "visible": True,
                "uv": [qwen_u, qwen_v],
                "u": qwen_u,
                "v": qwen_v,
                "coord_system": COORDINATE_SYSTEM,
                "depth": round(camera_depth, 3),
                "depth_kind": "camera_forward_z",
            }
            visible += 1
        else:
            objects[key] = _hidden_memory_record(
                center=center,
                robot_pos=robot_pos,
                robot_yaw_deg=robot_yaw_deg,
                robot_distance_m=robot_depth,
                reason=reason,
                cam=cam,
            )

        details[key] = {
            "visible": chosen is not None,
            "reason": reason,
            "category": str(meta.get("category", "gripper")),
            "scene_name": str(meta.get("scene_name", key)),
            "arm": meta.get("arm"),
            "point_kind": meta.get("point_kind"),
            "center_world": [round(float(x), 4) for x in center.tolist()],
            "robot_distance_m": round(robot_depth, 3),
            "robot_xy_distance_m": spin_hint.get("robot_xy_distance_m"),
            "approx_dir": spin_hint.get("approx_dir"),
            "spin_to_view_deg": spin_hint.get("spin_to_view_deg"),
            "relative_bearing_deg": spin_hint.get("relative_bearing_deg"),
            "target_yaw_deg": spin_hint.get("target_yaw_deg"),
            "bearing_world_deg": spin_hint.get("bearing_world_deg"),
            "pitch_to_view_deg": pitch_hint.get("pitch_to_view_deg"),
            "pitch_to_view_raw_deg": pitch_hint.get("pitch_to_view_raw_deg"),
            "target_pitch_deg": pitch_hint.get("target_pitch_deg"),
            "camera_pitch_deg": pitch_hint.get("camera_pitch_deg"),
            "pitch_hint_reason": pitch_hint.get("pitch_hint_reason"),
            "camera_depth_m": (
                round(float(chosen["camera_depth_m"]), 3) if chosen is not None else None
            ),
            "observed_depth_linear_m": (
                round(float(observed_depth), 3) if observed_depth is not None else None
            ),
        }

    return {
        "ok": True,
        "task": task_name,
        "task_instruction": _task_instruction(task_name),
        "updated_ts": time.time(),
        "tick": tick,
        "marked_places": _marked_places_lines(),
        "robot_pose": {
            "x": round(float(robot_pose.get("x", 0.0)), 4),
            "y": round(float(robot_pose.get("y", 0.0)), 4),
            "z": round(float(robot_pose.get("z", 0.0)), 4),
            "yaw_deg": round(float(robot_yaw_deg), 2),
            "source": robot_pose_source,
        },
        "robot_joints": robot_joints,
        "head_camera": {
            "ok": head is not None,
            "image_id": str(image_id or "") or None,
            "image_width": int(cam.get("image_width", 0) or 0),
            "image_height": int(cam.get("image_height", 0) or 0),
            "depth_source": depth_source,
            "binding": "capture_image" if image_id else "server_cache",
            "note": (
                "depth is head-camera forward z-depth in meters; every public uv "
                "uses Qwen3-VL relative coordinates"
            ),
            "coordinate_system": COORDINATE_SYSTEM,
            "coordinate_range": {
                "u": [0, _QWEN_UV_MAX],
                "v": [0, _QWEN_UV_MAX],
                "note": "pass MEMORY u/v directly to every public point-tool u/v",
            },
        },
        "summary": {
            "objects": total,
            "visible": visible,
            "hidden": max(0, total - visible),
            "depth_source": depth_source,
        },
        "objects": objects,
        "details": details,
    }


def _marked_places_lines() -> List[str]:
    """测试口 spatial_map 里 mark_on_map 标过的地点；未开启时为空。"""
    try:
        from behavior_interface.spatial_map import (
            places_memory_lines,
            spatial_map_enabled,
        )

        if not spatial_map_enabled():
            return []
        return places_memory_lines()
    except Exception:
        return []


def format_memory(mem: Dict[str, Any]) -> str:
    if isinstance(mem, dict) and "bddl_completion" in mem:
        return format_task_goals_only_memory(mem)
    if not mem or not mem.get("ok"):
        return "(memory unavailable)"
    head = mem.get("head_camera") or {}
    summary = mem.get("summary") or {}
    coord_range = head.get("coordinate_range") or {}
    u_range = coord_range.get("u") or [0, _QWEN_UV_MAX]
    v_range = coord_range.get("v") or [0, _QWEN_UV_MAX]
    coord_header = (
        "uv coordinate system: Qwen3-VL relative image coords; "
        "top-left=(0,0), bottom-right=(1000,1000)"
    )
    tool_coordinate_rule = (
        "tool coordinates: pass MEMORY u/v directly to every point-tool u/v; "
        "do not scale by image width or height"
    )
    instruction = str(mem.get("task_instruction") or _task_instruction(str(mem.get("task") or ""))).strip()
    lines = [
        f"Task instruction: {instruction}",
        "Task-related objects in head camera:",
        coord_header,
        f"uv nominal range: u={u_range[0]}..{u_range[1]}, v={v_range[0]}..{v_range[1]}; visible UVD is only emitted for non-clipped clickable points",
        tool_coordinate_rule,
        "visible object uvd is a visibility/centering/measurement candidate; clipped/offscreen centers are listed as not visible with a spin hint; for grasp planning, click a real target surface point in the current image, not necessarily the MEMORY center point",
        (
            "format: visible object: (u, v, depth_m) visibility point; hidden object: approx_dir + "
            "spin_to_view_deg + pitch_to_view_deg; depth_m = head camera forward z-depth (-z_cam); "
            "spin positive = turn left / counterclockwise; pitch positive = look up, negative = look down"
        ),
        (
            f"visible={summary.get('visible', 0)}/{summary.get('objects', 0)} "
            f"depth_source={head.get('depth_source', 'none')} "
            f"image={head.get('image_width', 0)}x{head.get('image_height', 0)}"
        ),
        "",
    ]
    objects = mem.get("objects") or {}
    details = mem.get("details") or {}
    for key in sorted(objects.keys()):
        val = objects.get(key)
        det = details.get(key) or {}
        label = key
        cat = det.get("category")
        if cat:
            label = f"{key} [{cat}]"
        if val is None:
            lines.append(f"- {label}: not visible; approx_dir=unknown, spin_to_view=unknown, pitch_to_view=unknown")
        elif val.get("visible") is False or val.get("uv") is None:
            spin = val.get("spin_to_view_deg", det.get("spin_to_view_deg"))
            if isinstance(spin, (int, float)) and math.isfinite(float(spin)):
                spin_s = f"{float(spin):+.1f}deg"
            else:
                spin_s = "unknown"
            pitch = val.get("pitch_to_view_deg", det.get("pitch_to_view_deg"))
            if isinstance(pitch, (int, float)) and math.isfinite(float(pitch)):
                pitch_s = f"{float(pitch):+.1f}deg"
            else:
                pitch_s = "unknown"
            direction = str(val.get("approx_dir") or det.get("approx_dir") or "unknown")
            xy_dist = val.get("robot_xy_distance_m", det.get("robot_xy_distance_m"))
            if isinstance(xy_dist, (int, float)) and math.isfinite(float(xy_dist)):
                dist_s = f"{float(xy_dist):.3f}m"
            else:
                dist_s = "?m"
            reason = str(val.get("reason") or det.get("reason") or "not_visible")
            lines.append(
                f"- {label}: not visible; approx_dir={direction}, "
                f"spin_to_view={spin_s}, pitch_to_view={pitch_s}, "
                f"xy_distance={dist_s}, reason={reason}"
            )
        else:
            uv = val.get("uv")
            if isinstance(uv, list) and len(uv) >= 2:
                u, v = uv[:2]
            else:
                u, v = val.get("u"), val.get("v")
            depth = val.get("depth")
            if isinstance(depth, (int, float)) and math.isfinite(float(depth)):
                depth_s = f"{float(depth):.3f}m"
            else:
                depth_s = "?"
            lines.append(f"- {label}: (u={u}, v={v}, depth={depth_s})")
    if not objects:
        lines.append("- no task-related objects")
    places = mem.get("marked_places") or []
    if places:
        lines.append("")
        lines.append("已标记地点（mark_on_map；spin 正=左转，可直接给 adjust_chassis）:")
        for line in places:
            lines.append(f"- {line}")
    return "\n".join(lines)


def _joint_unit(rec: Dict[str, Any], units: Dict[str, str]) -> str:
    jt = str(rec.get("type") or "")
    return str(units.get(jt) or "unit")


def _fmt_num(v: Any, ndigits: int = 4) -> str:
    try:
        f = float(v)
    except Exception:
        return "none"
    if not math.isfinite(f):
        return "none"
    return f"{f:.{ndigits}f}"


def _fmt_limit(limit: Any) -> str:
    if not isinstance(limit, dict):
        return "none"
    lo = limit.get("lower")
    hi = limit.get("upper")
    if lo is None and hi is None:
        return "continuous"
    return f"[{_fmt_num(lo, 3)},{_fmt_num(hi, 3)}]"


def _format_joint_record(rec: Dict[str, Any], units: Dict[str, str]) -> str:
    name = str(rec.get("joint") or "?")
    parent = str(rec.get("parent") or "?")
    child = str(rec.get("child") or "?")
    jt = str(rec.get("type") or "?")
    axis = rec.get("axis")
    axis_s = "?"
    if isinstance(axis, (list, tuple)) and len(axis) >= 3:
        axis_s = ",".join(_fmt_num(x, 0) for x in axis[:3])
    unit = _joint_unit(rec, units)
    q = rec.get("qpos")
    q_s = "none" if q is None else f"{_fmt_num(q, 4)} {unit}"
    return (
        f"  - {name} ({parent}->{child}, {jt}, axis={axis_s}, "
        f"limit={_fmt_limit(rec.get('limit'))}): {q_s}"
    )


def _format_robot_joint_observation(robot_joints: Dict[str, Any]) -> List[str]:
    if not robot_joints:
        return ["- unavailable"]
    units = robot_joints.get("units") or {}
    lines = [
        (
            f"source={robot_joints.get('source', 'unknown')} "
            f"urdf={robot_joints.get('urdf', '?')}"
        ),
        (
            f"observed={robot_joints.get('observed_count', 0)}/"
            f"{robot_joints.get('expected_count', 0)} "
            f"runtime_joints={robot_joints.get('runtime_joint_count', 0)} "
            f"units: revolute/continuous/virtual_revolute=rad, "
            f"prismatic/virtual_prismatic=m"
        ),
    ]
    groups = robot_joints.get("groups") or {}
    for group_name in ("base_pose", "trunk", "left_arm", "left_gripper", "right_arm", "right_gripper"):
        joints = list(groups.get(group_name) or [])
        if not joints:
            continue
        qvals = [
            "none" if rec.get("qpos") is None else _fmt_num(rec.get("qpos"), 4)
            for rec in joints
        ]
        lines.append(f"{group_name}: q=[{', '.join(qvals)}]")
        for rec in joints:
            lines.append(_format_joint_record(rec, units))
    fixed = list(robot_joints.get("fixed_relations") or [])
    if fixed:
        rel = []
        for rec in fixed:
            rel.append(
                f"{rec.get('joint')}({rec.get('parent')}->{rec.get('child')})"
            )
        lines.append("fixed link relations: " + "; ".join(rel))
    wheel_rel = list(robot_joints.get("urdf_wheel_relations") or [])
    if wheel_rel:
        rel = []
        for rec in wheel_rel:
            rel.append(
                f"{rec.get('joint')}({rec.get('parent')}->{rec.get('child')}, "
                f"{rec.get('type')}, axis={','.join(_fmt_num(x, 0) for x in (rec.get('axis') or [0, 0, 0])[:3])})"
            )
        lines.append("URDF physical wheel/steer relations (not runtime qpos names): " + "; ".join(rel))
    return lines
