"""v1 tool profile: compact public tool surface, same implementation logic."""

PUBLIC_SKILLS = (
    "capture",
    "capture_left_wrist_camera",
    "capture_right_wrist_camera",
    "move_base_to_point",
    "move_eef",
    "rotate_eef",
    "plan_move_eef",
    "move_in_world_coord",
    "move_in_robot_coord",
    "face_to_point",
    "adjust_plan_pose",
    "move_to_object_v2",
    "move_to_point_v2",
    "move_to_point_v3",
    "mesure_shoulder_distance",
    "plan_eef_v2",
    "exec_move_v2",
    "exec_eef_pose_v2",
    "set_arm_to_grasp_position",
    "reset_body",
    "diag_reset_object_diff",
    "diag_safe_back_scan",
)

LOAD_MODULES = (
    "move_to",
    "face_to_point",
    "move_eef",
    "plan_move_eef",
    "adjust_plan_pose",
    "rotate_eef",
    "viz_base_path_overlay",
    "capture",
    "wrist_grasp_zone_overlay",
    "wrist_metric_ruler",
    "wrist_capture",
    "move_base_to_point",
    "plan_eef_v2",
    "exec_move_v2",
    "exec_eef_pose_v2",
    "move_to_object_v2",
    "move_to_point_v2",
    "move_to_point_v3",
    "mesure_shoulder_distance",
    "wrist_j567_solver",
    "arm_reset",
    "reset_body",
    "diag_reset_object_diff",
    "diag_safe_back_scan",
)

# Hot reload still touches the full dependency chain used by the retained tools,
# especially the grasp filter and exec stack.  Extra registered diagnostics are
# pruned by PUBLIC_SKILLS after reload.
RELOAD_MODULES = (
    "grasp",
    "tuck_trajectory",
    "eef",
    "viz_eef_v2",
    "plan_grasp_gripper_geom",
    "plan_grasp_gripper_fit",
    "plan_grasp_opening_volume",
    "viz_gripper_overlay",
    "gripper_camera_face",
    "grasp_obj_pipeline_core",
    "grasp_obj_v7_gpu",
    "grasp_point_pipeline_core",
    "plan_press_point",
    "plan_grasp_object",
    "plan_grasp_point",
    "plan_grasp_core",
    "plan_eef_core",
    "trunk_vertical_lift",
    "move_to",
    "face_to_point",
    "move_eef",
    "plan_move_eef",
    "adjust_plan_pose",
    "rotate_eef",
    "viz_base_path_overlay",
    "capture",
    "wrist_grasp_zone_overlay",
    "wrist_metric_ruler",
    "wrist_capture",
    "plan_eef_v2",
    "exec_move_v2",
    "exec_eef_pose_v2",
    "base_chord_reach",
    "move_to_object_geom",
    "reach_point_pitch_recovery",
    "move_to_object_v2",
    "move_to_point_v2",
    # move_base_to_point 在模块级 from-import 了 move_to_point_v2._sphere_center_from_uv，
    # 必须排在其后 reload，否则热加载后它会继续持有旧的反投影实现。
    "move_base_to_point",
    "move_to_point_v3",
    "mesure_shoulder_distance",
    "wrist_j567_solver",
    "arm_reset",
    "reset_body",
    "diag_reset_object_diff",
    "diag_safe_back_scan",
)

V2_TOOL_NAMES = (
    "capture",
    "capture_left_wrist_camera",
    "capture_right_wrist_camera",
    "move_base_to_point",
    "move_eef",
    "rotate_eef",
    "plan_move_eef",
    "move_in_world_coord",
    "move_in_robot_coord",
    "face_to_point",
    "adjust_plan_pose",
    "move_to_object",
    "move_to_point",
    "mesure_shoulder_distance",
    "plan_grasp_point_filter",
    "plan_grasp_object_filter",
    "exec_move",
    "exec_eef_pose",
    "set_arm_to_grasp_position",
    "reset_body",
)
